docs: improve documenting
sibelius/relay-workshop pull request #729
Opened 2021-06-26 21:03 UTC by arantespp

# Summary

More readable MongoDB Docker commands.

2021-06-26 21:16 UTC, sibelius approved these changes

2021-10-18 01:38 UTC, tgmarinho requested changes
just improving some words! nice work @arantespp :)

2021-10-18 01:38 UTC, tgmarinho commented on README.md
> +- `PORT` is must be replace to the port that will you'll expose in your computer.
"is must be replaced with the port that will you'll expose in your computer."

2021-10-18 01:38 UTC, tgmarinho commented on README.md
> +- `CONTAINER_NAME` the name of the container that will be created.
container's name that will be created.

2023-12-01 12:07 UTC, closed without merging